### ISSUE TITLE
Fix existing endpoints

### ISSUE THREAD

**Issue by j-chad** [SE701-T5/Backend#100]
**Is your feature request related to a problem? Please describe.**
The backend endpoints are currently not consistently working and do not provide the front end with sufficient information.

**Describe the solution you'd like**
Add endpoints:
- [ ] `PATCH /api/v1/users/:id/communities`
- [ ] `GET /api/v1/users/:id/communities`

Verify functionality of the existing endpoints:
- [ ] `GET /api/v1/posts`
- [x] `POST /api/v1/posts`
- [x] `GET api/v1/posts/:id`
- [x] `PATCH api/v1/posts/:id`
- [x] `DELETE api/v1/posts/:id`
- [x] `GET /api/v1/posts/:id/comments`
- [x] `POST /api/v1/posts/:id/comments`
- [ ] `PATCH /api/v1/posts/:id/comments/:id`
- [x] `POST /api/v1/users`
- [x] `POST /api/v1/users/login`
- [x] `POST /api/v1/users/logout`
- [x] `GET /api/v1/users/:id`
- [x] `PATCH /api/v1/users/:id`
- [x] `DELETE /api/v1/users/:id`

**Additional context**
[FE Issue](https://github.com/SE701-T5/Frontend/issues/84)

### Checklist:

- [x] I have double-checked that the issue does not currently exist.
- [x] I have added the appropriate labels (e.g. bug, enhancement, new feature).
- [x] I have added the **Team 4** project

**Comment by justcrossheaven** [comment]
Update: For post endpoints, all users would have the ability to update/delete other user's post. (Not sure whether this should be fixed tho)

**Comment by justcrossheaven** [comment]
````
POST /api/v1/users : 
{
    "username":"john",
    "displayName":"lol",
    "email": "dev111@test.com",
    "plaintextPassword":"123456www"
}
````
````
POST /api/v1/users/login : 
{
    "username":"john",
    "plaintextPassword":"123456www"
}
````
````
POST /api/v1/posts
{
    "userID": "john's id",
    "communityID": "UOA",
    "title": "lol",
    "text": "lol",
    "images": ["image string"]
}
````
````
POST /api/v1/posts/:id/comments
{
    "authorID": "john's id",
    "username": "john",
    "title": "lol",
    "bodyText": "lol",
    "attachments": ["image"]
}
````

**Comment by ljey973** [comment]
Endpoint for updating a comment has been changed from : PATCH /api/v1/posts/:id/comments/:id to: PATCH /api/v1/posts/comments/:id

**Comment by justcrossheaven** [comment]
````
POST /api/v1/communities
{
    "userID": "623efb5efc2d42cdd9456ba2",
    "name": "uoa",
    "description": "akjsdhaskjdhaskd",
    "members": 25,
    "img": "ashdksjah"
}
````

**Comment by j-chad** [comment]
the members shouldn't be part of the post request

**Comment by j-chad** [comment]
also why does it need userid?

**Comment by justcrossheaven** [comment]
> also why does it need userid?

Should this endpoint be authenticated? If yes then it would need userID...

**Comment by j-chad** [comment]
that will be passed with the authentication header
